version: "3"

services:
  minio:
    image: minio/minio:latest # RELEASE.2021-11-24T23-19-33Z 
    container_name: minio
    ports:
     - "9000:9000"
     - "9090:9090"
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=ml_password"
    volumes:
      - minio_data:/data
    command: server /data --console-address "0.0.0.0:9090" --address "0.0.0.0:9000"

volumes:
  minio_data:
